### ISSUE TITLE
cyclone error

### ISSUE THREAD

**Issue by rehanzfr-zz** [MarioniLab/archive-scran#1]
Dear There I am following https://f1000research.com/articles/5-2122/v2. When I run 

assignments <- cyclone(sce, mm.pairs, gene.names=ensembl)

it gives me 

Error in .local(x, ...) : 
  length of 'gene.names' must be equal to 'x' nrows

Where everything is working until the command. Please help.

**Comment by LTLA** [comment]
Well, the cause is pretty much as the error message indicates. `ensembl` needs to be a character vector of length equal to the number of rows in `sce`. Is this the case in your analysis?

**Comment by rehanzfr-zz** [comment]
The lengths of ensemble and sce are same.

**Comment by LTLA** [comment]
Can you prepare a minimal working example that can reproduce the error? There's not a lot that can go wrong in that part of the code. The only thing I can think of is that you don't have a `counts` field in your `sce` object. I also assume that you're using the latest version of _scran_ and Bioconductor.

**Comment by rehanzfr-zz** [comment]
Yes I think I was using the the older version of scran i.e. 1.0.4. Will let you know after using upgraded. 

Thank you very much.

**Comment by LTLA** [comment]
I'm going to assume this was fixed, so I'm closing this issue.

**Comment by rehanzfr-zz** [comment]
Yes please close the issue as it was fixed


Assist. Prof. Dr Rehan Zafar ParachaRCMS, NUST
-------- Original message --------From: Aaron Lun <notifications@github.com> Date: 05/12/2016  7:46 p.m.  (GMT+05:00) To: MarioniLab/scran <scran@noreply.github.com> Cc: rehanzfr <rehanzfr@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MarioniLab/scran] cyclone error (#1) 
I'm going to assume this was fixed, so I'm closing this issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MarioniLab/scran","title":"MarioniLab/scran","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MarioniLab/scran"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LTLA in #1: I'm going to assume this was fixed, so I'm closing this issue."}],"action":{"name":"View Issue","url":"https://github.com/MarioniLab/scran/issues/1#issuecomment-264872081"}}}
