### ISSUE TITLE
No featureControlInfo

### ISSUE THREAD

**Issue by LeandroRitter** [MarioniLab/archive-scran#2]
Hi Aaron,

I am following the pipeine here https://github.com/MarioniLab/scran/blob/master/vignettes/scran.Rmd
and get an error when executing

library(scran)
sce <- newSCESet(countData=data.frame(all.counts))
sce <- calculateQCMetrics(sce, feature_controls=list(
    MySpikes=rep(c(FALSE, TRUE), c(ngenes, nspikes))
))
setSpike(sce) <- "MySpikes"

the function setSpike throws an error "Error in .get_feature_control_names(x) :  no slot of name "featureControlInfo" for this object of class "SCESet""

It looks like calculateQCMetrics does not add featureControlInfo to the SCESet object. I do not get this error when using isSpike installing scran with biocLite, but this Bioconductor version does not seem to be updated (i.e. compared to the github version) as it does not understand general.use=FALSE in the computeSpikeFactors. I wonder if you could fix those issues? Thanks!

Best,
Nikolay Oskolkov

**Comment by LTLA** [comment]
You seem to be using the development version of _scran_, which needs to be running the development version of _scater_ as well - see https://github.com/davismcc/scater. Be advised that Davis and I are going to do some major refactoring of the _scater_/_scran_ code over the holidays, so the GitHub versions may not be particularly stable.

**Comment by LeandroRitter** [comment]
Yes, that is correct, after I installed the scater package from github there was no problems with the general.use=FALSE in the calculateSpikeFactors. Thanks a lot!
I have one more question. Do I understand correctly that the lines

sce <- computeSpikeFactors(sce, general.use=FALSE)
sce <- normalize(sce)

are equivalent to applying computeSumFactors to gene.counts and spikes.counts and normalizing the matrix of counts for endogenous genes and matrix of counts of spikes separately and then applying rbind to the two matrices? Thanks!

Best,
Nikolay

**Comment by LTLA** [comment]
You're almost correct. The spike-in counts are normalized by the sum of the spike-in counts, i.e., the "spike-in library size", which is permissible because you shouldn't have any DE for the spike-in transcripts. Other than that, your description is basically correct.
