### ISSUE TITLE
Non-zero exit status on the Farm

### ISSUE THREAD

**Issue by cguzzo** [MarioniLab/archive-scran#4]
Hi,

I tried to install scran (Bioconductor) on the farm but get a non zero exit error whenever I try to install it. The problem seems to come from httpuv - when trying to update the package, I get the following error - cc1plus: error: unrecognised command line option ‘-std=gnu++11’ and then installation of package ‘httpuv’ had non-zero exit status.

I've tried to install it both on R3.3.2 an 3.4.1 - any ideas as to what might be going wrong?

Thanks!
Charlotte

**Comment by LTLA** [comment]
If I had to guess, I would say that your version of GCC is out of date and does not support the C++11 standard. _httpuv_ is a fairly common package, so I don't think this is a _scran_-specific problem.

**Comment by cguzzo** [comment]
Thanks, will check!

**Comment by LTLA** [comment]
Closing this issue. Note that _scran_ also requires C++11 (as does a whole bunch of other things it depends on, and probably half of Bioconductor) so it'd be better to upgrade sooner rather than later.
