### ISSUE TITLE
Versions and more

### ISSUE THREAD

**Issue by royfrancis** [MarioniLab/archive-scran#5]
I installed version `scran 1.2.2` from bioconductor. The online [vignette](http://bioconductor.org/packages/release/bioc/vignettes/scran/inst/doc/scran.html)(17-07-2017) is different from the vignette inside the package (18-01-2017). 

The 'newer' version (17-07-2017) of the vignette seems to be outdated. For example `setSpike()` doesn't seem to work. Instead I find only `isSpike()`.

**Comment by LTLA** [comment]
The latest version of _scran_ is 1.4.0, you'll need to update your version of R (to 3.4.*) and Bioconductor (currently release version 3.5).
