### ISSUE TITLE
Export normalised data

### ISSUE THREAD

**Issue by royfrancis** [MarioniLab/archive-scran#6]
Hi, How do I get normalised data out of scater to a regular R data.frame? Is this normalised data good for comparing sample-sample and gene-gene? I start with raw counts from Salmon. What is the difference between normalised counts and scaled TPM?

**Comment by LTLA** [comment]
Several suggestions:

1. One question at a time.
2. If you have a question about _scater_, put an issue about https://github.com/davismcc/scater.
3. If you have a question about _scran_, I prefer if you post on https://support.bioconductor.org.
